# It's good practice to include the Pod source in your Podfile
source 'https://github.com/CocoaPods/Specs.git'

# specify platform and target OS version
platform :ios, '7.0'

# this would be the relative path of your app, whatever that may be
xcodeproj 'SimplePubSub/SimplePubSub.xcodeproj'

# this is the relative location of your workspace, I prefer to explicity 
# indicate this, though it is not always required. Feel free to use whatever
# name for your workspace that you would like.
workspace 'Examples.xcworkspace'

# here we include the wonderful new PubNub pod
pod 'PubNub', '~> 4.0'