# Next line contains target platform settings
platform :ios, '8.0'
# Use dynamic Frameworks
use_frameworks!

# Target name
target 'cryptop' do
  # List of target dependencies
  pod 'ObjectiveSugar', '~> 1.1'
  pod 'ORStackView', '~> 3.0'
  pod 'RxSwift', '~> 2.6'
end